name: mergetest

on:
  pull_request:

jobs:
  run-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - uses: astral-sh/setup-uv@v4

      - name: Run test with uv (ephemeral deps)
        env:
          HF_HUB_DISABLE_TELEMETRY: "1"
        run: uv run --with huggingface_hub test.py